services:
  gosma:
    container_name: monitoring-goSMA
    image: ghcr.io/blccming/gosma:main
    restart: unless-stopped
    network_mode: "host" # necessary for networking metrics
    ports:
      - "8485:8485"
    volumes:
      - "/etc/os-release:/etc/os-release:ro" # provides the host's os instead of the container's
    environment:
      - PORT=8485 # standard goSMA port
      - UPDATE_INTERVALL=1 # standard: 1 second; can take floating point numbers
      - HOSTNAME # overwrites the hostname from /etc/hostname
